"""Mount handlers for Azure Blob Storage / Azure Files.

Supports three mount modes:

* ``blobfuse2`` — FUSE driver for Azure Blob containers (default)
* ``nfs``       — kernel NFSv4.1 mount for Azure Files Premium NFS shares
* ``smb``       — placeholder (not yet implemented)
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Optional

# Azure storage account / container naming: lowercase alphanumerics + hyphens,
# 3-63 chars, must start and end with alphanumeric. Disallow shell metachars,
# path traversal, whitespace, quotes, etc.
_AZ_NAME_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])?$")


def _validate_az_name(value: str) -> bool:
    """Return True if ``value`` is a valid Azure account/container name."""
    if not isinstance(value, str):
        return False
    return bool(_AZ_NAME_RE.match(value))

logger = logging.getLogger(__name__)

DEFAULT_MOUNT_PATH = os.environ.get("AZUREFILES_MOUNT_PATH", "/mnt/azurefiles")
FUSE_TMP_PATH = os.environ.get("AZUREFILES_FUSE_TMP_PATH", "/tmp/blobfuse2")


# ─── Helpers ────────────────────────────────────────────────────────────────


def _run(cmd: list[str]) -> subprocess.CompletedProcess:
    """Run a command, capturing output, never raising on non-zero exit."""
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=False)
    except Exception as e:
        logger.error("Command failed: %s: %s", " ".join(cmd), e)
        raise


def _is_mounted(mount_path: str) -> bool:
    """Return True if ``mount_path`` appears in /proc/mounts."""
    try:
        with open("/proc/mounts", "r") as f:
            for line in f:
                parts = line.split()
                if len(parts) >= 2 and parts[1] == mount_path:
                    return True
        return False
    except Exception:
        return False


def _check_blobfuse2_installed() -> bool:
    """Check whether the ``blobfuse2`` binary is on PATH."""
    return _run(["which", "blobfuse2"]).returncode == 0


def _install_blobfuse2() -> tuple[bool, str]:
    """Install blobfuse2 via the Microsoft apt repository.

    Returns:
        (success, message)
    """
    logger.info("Installing blobfuse2 via Microsoft apt repository...")
    script = (
        "set -e && "
        "sudo mkdir -p /etc/apt/keyrings && "
        "curl -sL https://packages.microsoft.com/keys/microsoft.asc "
        "| sudo gpg --dearmor --yes -o /etc/apt/keyrings/microsoft.gpg && "
        "source /etc/os-release && "
        "echo \"deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] "
        "https://packages.microsoft.com/repos/azure-cli/ ${VERSION_CODENAME} main\" "
        "| sudo tee /etc/apt/sources.list.d/azure-cli.list && "
        "echo \"deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] "
        "https://packages.microsoft.com/ubuntu/${VERSION_ID}/prod ${VERSION_CODENAME} main\" "
        "| sudo tee /etc/apt/sources.list.d/microsoft-prod.list && "
        "sudo apt-get update && sudo apt-get install -y blobfuse2"
    )
    result = _run(["bash", "-c", script])
    if result.returncode == 0 and _check_blobfuse2_installed():
        return True, "blobfuse2 installed successfully"
    if result.returncode == 0:
        return False, "Installer ran but blobfuse2 binary not found"
    return False, f"Installation failed: {result.stderr or result.stdout}"


def _write_fuse_config(
    yaml_path: str, account_name: str, container_name: str
) -> None:
    """Write a minimal blobfuse2 v2 YAML config to ``yaml_path``.

    Auth mode is hard-coded to ``managed_identity`` — the only auth path
    currently supported by this plugin.
    """
    Path(yaml_path).parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# Auto-generated by hermes-azure-files-plugin\n"
        "allow-other: true\n"
        "logging:\n"
        "  type: syslog\n"
        "  level: log_warning\n"
        "components:\n"
        "  - libfuse\n"
        "  - file_cache\n"
        "  - attr_cache\n"
        "  - azstorage\n"
        "azstorage:\n"
        "  type: block\n"
        f"  account-name: {account_name}\n"
        f"  container: {container_name}\n"
        "  mode: managed_identity\n"
        "  endpoint: https://" + account_name + ".blob.core.windows.net\n"
    )
    with open(yaml_path, "w") as f:
        f.write(content)


def _get_mount_info() -> list[dict]:
    """Parse /proc/mounts for blobfuse2 + Azure-files mounts."""
    mounts: list[dict] = []
    azure_fs = {"nfs", "nfs4"}
    try:
        with open("/proc/mounts", "r") as f:
            for line in f:
                parts = line.split()
                if len(parts) < 4:
                    continue
                device, mp, fstype, opts = parts[0], parts[1], parts[2], parts[3]
                is_blobfuse = "blobfuse2" in line
                is_azure_share = (
                    "file.core.windows.net" in device and fstype in azure_fs
                )
                if is_blobfuse or is_azure_share:
                    mounts.append(
                        {
                            "device": device,
                            "mount_path": mp,
                            "filesystem_type": fstype,
                            "mount_options": opts,
                        }
                    )
    except Exception as e:
        logger.error("Failed to parse /proc/mounts: %s", e)
    return mounts


# ─── Tool Handlers ──────────────────────────────────────────────────────────


def azurefiles_mount_handler(args, **kwargs) -> str:
    """Mount an Azure Blob container / Files share locally."""
    try:
        account_name = args.get("account_name")
        container_name = args.get("container_name")
        if not account_name:
            return json.dumps({"error": "account_name parameter is required"})
        if not container_name:
            return json.dumps({"error": "container_name parameter is required"})

        if not _validate_az_name(account_name):
            return json.dumps(
                {
                    "error": f"Invalid account_name '{account_name}'",
                    "hint": (
                        "Azure account names must be 3-63 chars, lowercase "
                        "alphanumerics and hyphens, starting/ending with "
                        "alphanumeric (regex: ^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])?$)."
                    ),
                }
            )
        if not _validate_az_name(container_name):
            return json.dumps(
                {
                    "error": f"Invalid container_name '{container_name}'",
                    "hint": (
                        "Container names must be 3-63 chars, lowercase "
                        "alphanumerics and hyphens, starting/ending with "
                        "alphanumeric. No spaces, quotes, slashes, or '..'."
                    ),
                }
            )

        mode = args.get("mode", "blobfuse2")
        if mode not in ("blobfuse2", "nfs", "smb"):
            return json.dumps(
                {"error": f"Invalid mode '{mode}'. Must be one of: blobfuse2, nfs, smb"}
            )

        auth = args.get("auth", "managed_identity")
        if auth != "managed_identity":
            return json.dumps(
                {
                    "error": f"Invalid auth '{auth}'. Only 'managed_identity' is currently supported.",
                    "hint": "Use auth='managed_identity' (default).",
                }
            )

        mount_path = args.get(
            "mount_path", f"{DEFAULT_MOUNT_PATH}/{account_name}/{container_name}"
        )

        if _is_mounted(mount_path):
            return json.dumps(
                {
                    "success": True,
                    "message": f"Already mounted at {mount_path}",
                    "mount_path": mount_path,
                    "account_name": account_name,
                    "container_name": container_name,
                    "mode": mode,
                }
            )

        # SMB not implemented
        if mode == "smb":
            return json.dumps(
                {
                    "error": "SMB mount not yet implemented; use blobfuse2 or nfs mode",
                    "hint": "Pass mode='blobfuse2' (default) or mode='nfs'",
                }
            )

        _run(["sudo", "mkdir", "-p", mount_path])

        if mode == "blobfuse2":
            if not _check_blobfuse2_installed():
                ok, msg = _install_blobfuse2()
                if not ok:
                    return json.dumps(
                        {
                            "error": f"blobfuse2 not installed: {msg}",
                            "hint": "Run azurefiles_setup first, or install blobfuse2 manually.",
                        }
                    )

            yaml_path = f"{FUSE_TMP_PATH}/{container_name}.yaml"
            try:
                _write_fuse_config(yaml_path, account_name, container_name)
            except Exception as e:
                return json.dumps({"error": f"Failed to write fuse config: {e}"})

            mount_cmd = [
                "sudo",
                "blobfuse2",
                "mount",
                mount_path,
                f"--config-file={yaml_path}",
            ]
            result = _run(mount_cmd)
            if result.returncode == 0:
                return json.dumps(
                    {
                        "success": True,
                        "message": f"Successfully mounted {account_name}/{container_name} at {mount_path}",
                        "mount_path": mount_path,
                        "account_name": account_name,
                        "container_name": container_name,
                        "mode": mode,
                    }
                )
            return json.dumps(
                {
                    "error": f"blobfuse2 mount failed: {result.stderr or result.stdout}",
                    "hint": (
                        "Check: 1) account/container exist, 2) auth identity has "
                        "'Storage Blob Data Contributor' role, 3) network egress allowed."
                    ),
                }
            )

        # mode == "nfs"
        remote = f"{account_name}.file.core.windows.net:/{account_name}/{container_name}"
        mount_cmd = [
            "sudo",
            "mount",
            "-t",
            "nfs",
            "-o",
            "vers=4,minorversion=1,sec=sys",
            remote,
            mount_path,
        ]
        result = _run(mount_cmd)
        if result.returncode == 0:
            return json.dumps(
                {
                    "success": True,
                    "message": f"Successfully mounted {remote} at {mount_path}",
                    "mount_path": mount_path,
                    "account_name": account_name,
                    "container_name": container_name,
                    "mode": mode,
                }
            )
        return json.dumps(
            {
                "error": f"NFS mount failed: {result.stderr or result.stdout}",
                "hint": (
                    "Azure Files NFS requires: Premium FileStorage account, NFS share, "
                    "and TCP/2049 reachable from this VNet."
                ),
            }
        )

    except Exception as e:
        return json.dumps({"error": f"Mount failed: {str(e)}"})


def azurefiles_unmount_handler(args, **kwargs) -> str:
    """Unmount an Azure Files / blobfuse2 mount point."""
    try:
        mount_path = args.get("mount_path")
        if not mount_path:
            return json.dumps({"error": "mount_path parameter is required"})

        if not _is_mounted(mount_path):
            return json.dumps(
                {
                    "success": True,
                    "message": f"Path {mount_path} is not currently mounted",
                }
            )

        result = _run(["sudo", "umount", mount_path])
        if result.returncode == 0:
            return json.dumps(
                {
                    "success": True,
                    "message": f"Successfully unmounted {mount_path}",
                    "mount_path": mount_path,
                }
            )
        return json.dumps(
            {
                "error": f"Failed to unmount {mount_path}: {result.stderr or result.stdout}",
                "hint": "If busy, try: sudo umount -l <path> (lazy unmount)",
            }
        )
    except Exception as e:
        return json.dumps({"error": f"Unmount failed: {str(e)}"})


def azurefiles_status_handler(args, **kwargs) -> str:
    """List currently mounted blobfuse2 / Azure-files mounts."""
    try:
        mounts = _get_mount_info()
        return json.dumps(
            {
                "success": True,
                "mounts": mounts,
                "count": len(mounts),
                "message": (
                    f"Found {len(mounts)} Azure-files mount(s)"
                    if mounts
                    else "No Azure-files mounts found"
                ),
            }
        )
    except Exception as e:
        return json.dumps({"error": f"Status check failed: {str(e)}"})


def azurefiles_setup_handler(args, **kwargs) -> str:
    """Verify (and install) prerequisites for Azure Files mounts."""
    try:
        checks: dict = {}

        # az CLI present?
        az_present = _run(["which", "az"]).returncode == 0
        if az_present:
            cred = _run(["az", "account", "show"])
            checks["az_cli"] = {
                "ok": True,
                "detail": "az CLI available",
            }
            checks["credentials"] = {
                "ok": cred.returncode == 0,
                "detail": (
                    "Azure credentials available (az account show OK)"
                    if cred.returncode == 0
                    else "Not logged in. Run: az login (or use Managed Identity)"
                ),
            }
        else:
            checks["az_cli"] = {"ok": False, "detail": "az CLI not found"}
            checks["credentials"] = {
                "ok": False,
                "detail": "az CLI not installed — cannot verify credentials",
            }

        # blobfuse2
        if _check_blobfuse2_installed():
            checks["blobfuse2"] = {
                "ok": True,
                "detail": "blobfuse2 already installed",
            }
        else:
            ok, msg = _install_blobfuse2()
            checks["blobfuse2"] = {"ok": ok, "detail": msg}

        # default mount dir
        try:
            _run(["sudo", "mkdir", "-p", DEFAULT_MOUNT_PATH])
            checks["mount_directory"] = {
                "ok": True,
                "detail": f"{DEFAULT_MOUNT_PATH} exists",
            }
        except Exception as e:
            checks["mount_directory"] = {"ok": False, "detail": str(e)}

        all_ok = all(c["ok"] for c in checks.values())
        return json.dumps(
            {
                "success": all_ok,
                "message": (
                    "All prerequisites met — ready to mount"
                    if all_ok
                    else "Some checks failed — see details"
                ),
                "checks": checks,
                "next_step": (
                    "Use azurefiles_mount with account_name + container_name"
                    if all_ok
                    else "Fix the failed checks above, then retry"
                ),
            }
        )
    except Exception as e:
        return json.dumps({"error": f"Setup failed: {str(e)}"})


# ─── Tool Schemas ───────────────────────────────────────────────────────────

AZUREFILES_MOUNT_SCHEMA = {
    "name": "azurefiles_mount",
    "description": (
        "Mount an Azure Blob container or Azure Files share as a local directory. "
        "Supports blobfuse2 (default), NFS v4.1, or SMB (planned)."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "account_name": {
                "type": "string",
                "description": "Azure storage account name (e.g., 'mystorageacct').",
            },
            "container_name": {
                "type": "string",
                "description": "Blob container or file share name.",
            },
            "mount_path": {
                "type": "string",
                "description": (
                    f"Local mount path (default: {DEFAULT_MOUNT_PATH}/<account>/<container>)."
                ),
            },
            "mode": {
                "type": "string",
                "enum": ["blobfuse2", "nfs", "smb"],
                "description": "Mount driver to use (default: blobfuse2).",
            },
            "auth": {
                "type": "string",
                "enum": ["managed_identity"],
                "description": "Authentication method for blobfuse2 (only 'managed_identity' is supported; default).",
            },
        },
        "required": ["account_name", "container_name"],
    },
}

AZUREFILES_UNMOUNT_SCHEMA = {
    "name": "azurefiles_unmount",
    "description": "Unmount an Azure Files / blobfuse2 mount point.",
    "parameters": {
        "type": "object",
        "properties": {
            "mount_path": {
                "type": "string",
                "description": "Local mount path to unmount.",
            }
        },
        "required": ["mount_path"],
    },
}

AZUREFILES_STATUS_SCHEMA = {
    "name": "azurefiles_status",
    "description": "Show all currently mounted Azure-files / blobfuse2 mounts.",
    "parameters": {"type": "object", "properties": {}},
}

AZUREFILES_SETUP_SCHEMA = {
    "name": "azurefiles_setup",
    "description": (
        "Install blobfuse2 and verify az-CLI / credentials. "
        "Run this before the first mount."
    ),
    "parameters": {"type": "object", "properties": {}},
}
